# ════════════════════════════════════════════════════════════════════════════
# SecureMail-Frontend — Multi-stage Dockerfile
# Service: Next.js 16 (standalone output mode)
# Port:    3001
#
# IMPORTANT: NEXT_PUBLIC_* variables are baked into the JS bundle at build time.
# Override via build arg: docker build --build-arg NEXT_PUBLIC_API_URL=http://...
# ════════════════════════════════════════════════════════════════════════════

# ── Stage 1: Install dependencies ────────────────────────────────────────────
FROM node:22-alpine AS deps

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app

# Copy lockfiles for cache efficiency
COPY package.json pnpm-lock.yaml ./

# Install all dependencies (devDeps needed for build)
RUN pnpm install --frozen-lockfile --legacy-peer-deps


# ── Stage 2: Build Next.js application ───────────────────────────────────────
FROM node:22-alpine AS builder

RUN npm install -g pnpm

WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy entire source
COPY . .

# NEXT_PUBLIC_API_URL is baked into the bundle at build time.
# Browser-facing URL — always the host machine's address since
# the frontend uses client-side axios (no server-side API calls).
ARG NEXT_PUBLIC_API_URL=http://localhost:3000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV BUILD_STANDALONE=true

# Build produces .next/standalone/ due to next.config.ts output: "standalone"
RUN pnpm build


# ── Stage 3: Minimal production runtime ──────────────────────────────────────
# Next.js standalone output is a self-contained server.js + bundled node_modules
FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production \
    PORT=3001 \
    HOSTNAME=0.0.0.0

# Copy the minimal standalone server output
COPY --from=builder /app/.next/standalone ./

# Copy static assets (NOT included in standalone by default)
COPY --from=builder /app/.next/static ./.next/static

# Copy public directory (icons, images, etc.)
COPY --from=builder /app/public ./public

# Non-root user
RUN addgroup -S nextgroup && adduser -S -G nextgroup nextuser
USER nextuser

EXPOSE 3001

# server.js is the entrypoint generated by Next.js standalone output
CMD ["node", "server.js"]
