import { Email } from "@/types/mail";

export const mockEmails: Email[] = [
  {
    id: "1",
    subject:
      "Valued Investor, join us live tomorrow to explore Excel features!",
    bodyText:
      "Dear valued investor, we would like to invite you to our upcoming live webinar...",
    sender: "Amazon",
    senderEmail: "notifications@amazon.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "02:10 PM",
    hasAttachment: false,
  },
  {
    id: "2",
    subject:
      "Valued Investor, join us live tomorrow to explore Excel features!",
    bodyText:
      "Dear valued investor, we would like to invite you to our upcoming live webinar...",
    sender: "Amazon",
    senderEmail: "notifications@amazon.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "02:10 PM",
    hasAttachment: false,
  },
  {
    id: "3",
    subject: "Mohamed Mansor sent you add request",
    bodyText: "Mohamed Mansor wants to connect with you on LinkedIn...",
    sender: "Linked in",
    senderEmail: "notifications@linkedin.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "11:00 PM",
    hasAttachment: false,
  },
  {
    id: "4",
    subject: "Don't Miss This Only Promotion For The Year!",
    bodyText:
      "This is your last chance to grab our biggest discount of the year...",
    sender: "Gurifocus",
    senderEmail: "promo@gurifocus.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "Yesterday",
    hasAttachment: false,
  },
  {
    id: "5",
    subject: "Salaman Mohamed UI/UX designer sent you add request",
    bodyText: "Salaman Mohamed wants to connect with you...",
    sender: "Linked in",
    senderEmail: "notifications@linkedin.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "Yesterday",
    hasAttachment: false,
  },
  {
    id: "6",
    subject: "Time to celebrate your success",
    bodyText:
      "Congratulations! You've reached a new milestone in your writing journey...",
    sender: "Grammerly",
    senderEmail: "success@grammarly.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "4 Jan 2026",
    hasAttachment: false,
  },
  {
    id: "7",
    subject:
      "Your order No. 12456 shipped successfully, expected 12 Mar 2025 at 12:pm",
    bodyText: "Great news! Your order has been shipped and is on its way...",
    sender: "Temu",
    senderEmail: "orders@temu.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "1 Jan 2026",
    hasAttachment: true,
    attachmentName: "Document.pdf",
  },
  {
    id: "8",
    subject: "Goodmockups - new message",
    bodyText: "You have a new message from Goodmockups community...",
    sender: "Follow.it",
    senderEmail: "notifications@follow.it",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "15 Dec 2025",
    hasAttachment: false,
  },
  {
    id: "9",
    subject:
      "Your order No. 12456 shipped successfully, expected 12 Mar 2025 at 12:pm",
    bodyText: "Great news! Your order has been shipped and is on its way...",
    sender: "Temu",
    senderEmail: "orders@temu.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "08 Dec 2025",
    hasAttachment: false,
  },
  {
    id: "10",
    subject:
      "Your order No. 12456 shipped successfully, expected 12 Mar 2025 at 12:pm",
    bodyText: "Great news! Your order has been shipped and is on its way...",
    sender: "Temu",
    senderEmail: "orders@temu.com",
    isRead: true,
    isStarred: true,
    folder: "inbox",
    classification: "primary",
    date: "08 Dec 2025",
    hasAttachment: false,
  },
  {
    id: "11",
    subject: "New features available in your dashboard",
    bodyText: "We've just released some exciting new features...",
    sender: "Vercel",
    senderEmail: "updates@vercel.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "05 Dec 2025",
    hasAttachment: false,
  },
  {
    id: "12",
    subject: "Your weekly security report is ready",
    bodyText: "Here's your weekly security summary...",
    sender: "SecureMail",
    senderEmail: "reports@securemail.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "03 Dec 2025",
    hasAttachment: true,
    attachmentName: "Report.pdf",
  },
  {
    id: "13",
    subject: "Action required: Verify your email address",
    bodyText: "Please verify your email to continue using our services...",
    sender: "GitHub",
    senderEmail: "noreply@github.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "01 Dec 2025",
    hasAttachment: false,
  },
  {
    id: "14",
    subject: "Your subscription has been renewed",
    bodyText:
      "Your premium plan has been successfully renewed for another month...",
    sender: "Spotify",
    senderEmail: "billing@spotify.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "28 Nov 2025",
    hasAttachment: false,
  },
  {
    id: "15",
    subject: "Invitation: Design review meeting",
    bodyText: "You're invited to join the design review meeting on Friday...",
    sender: "Google Calendar",
    senderEmail: "calendar@google.com",
    isRead: false,
    isStarred: true,
    folder: "inbox",
    classification: "primary",
    date: "25 Nov 2025",
    hasAttachment: false,
  },
  {
    id: "16",
    subject: "Your cloud storage is 90% full",
    bodyText: "You're running low on storage space. Consider upgrading...",
    sender: "Google Drive",
    senderEmail: "drive@google.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "22 Nov 2025",
    hasAttachment: false,
  },
  {
    id: "17",
    subject: "New login detected from Cairo, Egypt",
    bodyText:
      "We noticed a new login to your account from a device in Cairo...",
    sender: "Microsoft",
    senderEmail: "security@microsoft.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "20 Nov 2025",
    hasAttachment: false,
  },
  {
    id: "18",
    subject: "Weekend sale: Up to 70% off everything",
    bodyText: "Don't miss our biggest sale of the season...",
    sender: "Nike",
    senderEmail: "deals@nike.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "18 Nov 2025",
    hasAttachment: false,
  },
  {
    id: "19",
    subject: "Your package has been delivered",
    bodyText: "Your package was delivered to your front door at 2:30 PM...",
    sender: "Amazon",
    senderEmail: "shipping@amazon.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "15 Nov 2025",
    hasAttachment: false,
  },
  {
    id: "20",
    subject: "Complete your profile to unlock features",
    bodyText:
      "You're almost there! Complete your profile to unlock premium features...",
    sender: "Figma",
    senderEmail: "team@figma.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "primary",
    date: "12 Nov 2025",
    hasAttachment: false,
  },

  // ===== إيميلات ترويجية (Promotions) =====
  {
    id: "21",
    subject: "Flash Sale! 50% off all courses this weekend only",
    bodyText: "Enroll in any course this weekend and get 50% off...",
    sender: "Udemy",
    senderEmail: "promotions@udemy.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "02:00 PM",
    hasAttachment: false,
  },
  {
    id: "22",
    subject: "New arrivals just for you - Shop now",
    bodyText: "Check out the latest collection curated just for you...",
    sender: "Zara",
    senderEmail: "shop@zara.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "01:30 PM",
    hasAttachment: false,
  },
  {
    id: "23",
    subject: "Your exclusive member discount is waiting",
    bodyText: "As a valued member, enjoy an exclusive 30% discount...",
    sender: "Amazon",
    senderEmail: "deals@amazon.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "Yesterday",
    hasAttachment: false,
  },
  {
    id: "24",
    subject: "Limited time: Free shipping on all orders",
    bodyText: "Order today and enjoy free shipping worldwide...",
    sender: "AliExpress",
    senderEmail: "offers@aliexpress.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "Yesterday",
    hasAttachment: false,
  },
  {
    id: "25",
    subject: "Upgrade your plan - Save 40% annually",
    bodyText: "Switch to our annual plan and save big...",
    sender: "Notion",
    senderEmail: "billing@notion.so",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "3 Jan 2026",
    hasAttachment: false,
  },
  {
    id: "26",
    subject: "Black Friday deals are back! Don't miss out",
    bodyText: "Our biggest deals of the year are here again...",
    sender: "Best Buy",
    senderEmail: "deals@bestbuy.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "2 Jan 2026",
    hasAttachment: false,
  },
  {
    id: "27",
    subject: "Earn double points this week only",
    bodyText: "Shop now and earn double loyalty points on every purchase...",
    sender: "Starbucks",
    senderEmail: "rewards@starbucks.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "1 Jan 2026",
    hasAttachment: false,
  },
  {
    id: "28",
    subject: "Your cart is waiting - Complete your purchase",
    bodyText:
      "You left some items in your cart. Complete your order before they sell out...",
    sender: "eBay",
    senderEmail: "reminders@ebay.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "promotions",
    date: "30 Dec 2025",
    hasAttachment: false,
  },

  // ===== إيميلات اجتماعية (Social) =====
  {
    id: "29",
    subject: "Ahmed liked your post",
    bodyText: "Ahmed liked your recent post about frontend development...",
    sender: "Twitter",
    senderEmail: "notifications@twitter.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "social",
    date: "03:00 PM",
    hasAttachment: false,
  },
  {
    id: "30",
    subject: "You have 5 new followers this week",
    bodyText: "Your profile is gaining traction! You got 5 new followers...",
    sender: "Instagram",
    senderEmail: "notifications@instagram.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "social",
    date: "01:00 PM",
    hasAttachment: false,
  },
  {
    id: "31",
    subject: "Sara commented on your photo",
    bodyText: "Sara left a comment: 'Amazing shot! Where was this taken?'",
    sender: "Facebook",
    senderEmail: "notifications@facebook.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "social",
    date: "Yesterday",
    hasAttachment: false,
  },
  {
    id: "32",
    subject: "Your friend Mohamed joined LinkedIn",
    bodyText:
      "Your friend Mohamed just joined LinkedIn. Send them a welcome message...",
    sender: "Linked in",
    senderEmail: "connections@linkedin.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "social",
    date: "2 Jan 2026",
    hasAttachment: false,
  },
  {
    id: "33",
    subject: "New mention in Design Community",
    bodyText: "Someone mentioned you in the Design Community group...",
    sender: "Discord",
    senderEmail: "notifications@discord.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "social",
    date: "30 Dec 2025",
    hasAttachment: false,
  },

  // ===== إيميلات التحديثات (Updates) =====
  {
    id: "34",
    subject: "System maintenance scheduled for Jan 15",
    bodyText: "We will be performing scheduled maintenance on January 15th...",
    sender: "AWS",
    senderEmail: "updates@aws.amazon.com",
    isRead: false,
    isStarred: false,
    folder: "inbox",
    classification: "updates",
    date: "Today",
    hasAttachment: false,
  },
  {
    id: "35",
    subject: "Your monthly statement is ready",
    bodyText: "Your January statement is now available to view online...",
    sender: "Bank of Egypt",
    senderEmail: "statements@boe.com",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "updates",
    date: "Yesterday",
    hasAttachment: true,
    attachmentName: "Statement.pdf",
  },
  {
    id: "36",
    subject: "App version 3.2.0 is now available",
    bodyText:
      "A new version of our app is available with bug fixes and improvements...",
    sender: "VSCode",
    senderEmail: "updates@vscode.dev",
    isRead: true,
    isStarred: false,
    folder: "inbox",
    classification: "updates",
    date: "3 Jan 2026",
    hasAttachment: false,
  },

  // ===== إيميلات مرسلة (Sent) =====
  {
    id: "37",
    subject: "Re: Meeting tomorrow at 3 PM",
    bodyText: "Sure, I'll be there. See you tomorrow!",
    sender: "Me",
    senderEmail: "mohamedhasabelnaby@gmail.com",
    isRead: true,
    isStarred: false,
    folder: "sent",
    classification: "primary",
    date: "Today",
    hasAttachment: false,
  },
  {
    id: "38",
    subject: "Project proposal - SecureMail v2",
    bodyText:
      "Hi team, please find attached the project proposal for SecureMail v2...",
    sender: "Me",
    senderEmail: "mohamedhasabelnaby@gmail.com",
    isRead: true,
    isStarred: true,
    folder: "sent",
    classification: "primary",
    date: "Yesterday",
    hasAttachment: true,
    attachmentName: "Proposal.pdf",
  },
  {
    id: "39",
    subject: "Re: Design feedback needed",
    bodyText: "I've reviewed the designs and left my comments on Figma...",
    sender: "Me",
    senderEmail: "mohamedhasabelnaby@gmail.com",
    isRead: true,
    isStarred: false,
    folder: "sent",
    classification: "primary",
    date: "3 Jan 2026",
    hasAttachment: false,
  },
  {
    id: "40",
    subject: "Invoice #2024-089",
    bodyText: "Please find attached the invoice for the completed work...",
    sender: "Me",
    senderEmail: "mohamedhasabelnaby@gmail.com",
    isRead: true,
    isStarred: false,
    folder: "sent",
    classification: "primary",
    date: "1 Jan 2026",
    hasAttachment: true,
    attachmentName: "Invoice.pdf",
  },

  // ===== إيميلات سبام (Spam) =====
  {
    id: "41",
    subject: "You've won $1,000,000! Claim now!",
    bodyText: "Congratulations! You've been selected as the winner of...",
    sender: "Prize Center",
    senderEmail: "winner@totallylegit.com",
    isRead: false,
    isStarred: false,
    folder: "spam",
    classification: "primary",
    date: "Today",
    hasAttachment: false,
  },
  {
    id: "42",
    subject: "URGENT: Your account will be suspended",
    bodyText: "Your account requires immediate verification or it will be...",
    sender: "Security Alert",
    senderEmail: "alert@not-real-bank.com",
    isRead: false,
    isStarred: false,
    folder: "spam",
    classification: "primary",
    date: "Yesterday",
    hasAttachment: false,
  },

  // ===== إيميلات تصيد (Phishing) =====
  {
    id: "43",
    subject: "Security Update: Reset your PayPal password immediately",
    bodyText: "We have detected unusual activity on your PayPal account. Please click here to reset your password...",
    sender: "PayPal Security",
    senderEmail: "security-update@paypa1-support.com",
    isRead: false,
    isStarred: false,
    folder: "phishing",
    classification: "primary",
    date: "Today",
    hasAttachment: false,
  },
  {
    id: "44",
    subject: "Action Required: Microsoft 365 Account Expiration",
    bodyText: "Your Microsoft 365 subscription will expire in 24 hours. Please update your billing information...",
    sender: "Microsoft Support",
    senderEmail: "admin@micro-soft-billing.com",
    isRead: true,
    isStarred: false,
    folder: "phishing",
    classification: "primary",
    date: "Yesterday",
    hasAttachment: false,
  },
  {
    id: "45",
    subject: "You received a secure document via DocuSign",
    bodyText: "Please review and sign the attached document. Click the link below to access...",
    sender: "DocuSign Service",
    senderEmail: "noreply@docusign-docs-secure.net",
    isRead: false,
    isStarred: false,
    folder: "phishing",
    classification: "primary",
    date: "2 days ago",
    hasAttachment: true,
    attachmentName: "Important_Contract.pdf",
  },

  // ===== إيميلات برمجيات خبيثة (Malware) =====
  {
    id: "46",
    subject: "Invoice #98234 Payment Overdue",
    bodyText: "Please find attached the overdue invoice #98234. Immediate payment is required to avoid service interruption...",
    sender: "Billing Department",
    senderEmail: "billing@finance-dept-services.com",
    isRead: false,
    isStarred: false,
    folder: "malware",
    classification: "primary",
    date: "Today",
    hasAttachment: true,
    attachmentName: "Invoice_98234.exe",
  },
  {
    id: "47",
    subject: "Urgent: Your device has been infected",
    bodyText: "We have detected multiple viruses on your system. Download the attached removal tool immediately to clean your PC...",
    sender: "IT Security Team",
    senderEmail: "support@antivirus-alert-system.net",
    isRead: true,
    isStarred: false,
    folder: "malware",
    classification: "primary",
    date: "Yesterday",
    hasAttachment: true,
    attachmentName: "RemovalTool.zip",
  },
  {
    id: "48",
    subject: "New Voicemail Message from +1 (555) 019-2384",
    bodyText: "You have received a new voice message. Length: 02:14. Click the attachment to listen to the recording...",
    sender: "PBX Phone System",
    senderEmail: "voicemail@pbx-internal.com",
    isRead: false,
    isStarred: false,
    folder: "malware",
    classification: "primary",
    date: "3 days ago",
    hasAttachment: true,
    attachmentName: "VoiceMessage.vbs",
  }
];
