import { NotificationsResponse } from "@/APIs/types/Notification";

export const MOCK_NOTIFICATIONS: NotificationsResponse = {
  data: [
    {
      id: 1,
      title: "New Login Detected",
      message: "A new login was detected from a new IP address in Paris, France.",
      type: "warning",
      category: "system",
      isRead: false,
      createdAt: "2026-05-02T10:30:00Z",
      link: "/settings",
    },
    {
      id: 2,
      title: "Phishing Attempt Blocked",
      message: "SecureMail successfully blocked a suspected phishing attempt targeting your Inbox.",
      type: "success",
      category: "threats",
      isRead: true,
      createdAt: "2026-05-01T15:45:00Z",
    },
    {
      id: 3,
      title: "Mailbox Sync Failed",
      message: "Failed to synchronize with your Outlook mailbox. Please re-authenticate.",
      type: "error",
      category: "system",
      isRead: false,
      createdAt: "2026-04-30T09:15:00Z",
      link: "/mailboxes",
    },
    {
      id: 4,
      title: "Security Update Available",
      message: "A new security patch is available for your account. Please update now.",
      type: "info",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-29T11:20:00Z",
    },
    {
      id: 5,
      title: "Account Password Changed",
      message: "Your password was recently changed. If this wasn't you, please secure your account.",
      type: "warning",
      category: "system",
      isRead: true,
      createdAt: "2026-04-28T14:20:00Z",
    },
    {
      id: 6,
      title: "Suspicious Activity Detected",
      message: "Our systems noticed unusual activity on your account. Review your recent logs.",
      type: "error",
      category: "threats",
      isRead: false,
      createdAt: "2026-04-27T18:50:00Z",
      link: "/settings",
    },
    {
      id: 7,
      title: "New Integration Connected",
      message: "You've successfully connected Slack to your SecureMail account.",
      type: "success",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-26T20:10:00Z",
    },
    {
      id: 8,
      title: "Backup Completed",
      message: "Your weekly data backup has finished successfully.",
      type: "success",
      category: "system",
      isRead: true,
      createdAt: "2026-04-25T09:00:00Z",
    },
    {
      id: 9,
      title: "Storage Almost Full",
      message: "Your storage is 90% full. Upgrade your plan to avoid service interruption.",
      type: "warning",
      category: "system",
      isRead: false,
      createdAt: "2026-04-24T12:00:00Z",
      link: "/billing",
    },
    {
      id: 10,
      title: "Feature Update: Dark Mode",
      message: "Dark mode is now available! Toggle it in your appearance settings.",
      type: "info",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-23T16:30:00Z",
    },
    {
      id: 11,
      title: "Two-Factor Auth Enabled",
      message: "You have successfully enabled two-factor authentication on your account.",
      type: "success",
      category: "system",
      isRead: true,
      createdAt: "2026-04-22T22:45:00Z",
    },
    {
      id: 12,
      title: "API Access Revoked",
      message: "Access for 'Third Party App' has been revoked due to inactivity.",
      type: "info",
      category: "system",
      isRead: true,
      createdAt: "2026-04-22T02:00:00Z",
    },
    {
      id: 13,
      title: "Email Campaign Finished",
      message: "Your security awareness campaign has concluded. View the results now.",
      type: "success",
      category: "system",
      isRead: true,
      createdAt: "2026-04-21T10:15:00Z",
    },
    {
      id: 14,
      title: "New Device Registered",
      message: "A new iPhone 15 was registered to your account.",
      type: "warning",
      category: "system",
      isRead: false,
      createdAt: "2026-04-20T19:30:00Z",
    },
    {
      id: 15,
      title: "Welcome to SecureMail",
      message: "Thanks for choosing SecureMail. Your journey to safe communication starts here.",
      type: "info",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-19T08:00:00Z",
    },
    {
      id: 16,
      title: "Pro Plan Subscription Active",
      message: "Your Pro Plan subscription is now active. Enjoy premium features!",
      type: "success",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-18T10:00:00Z",
    },
    {
      id: 17,
      title: "Beta Program Invitation",
      message: "You've been invited to join our exclusive beta program for AI features.",
      type: "info",
      category: "updates",
      isRead: false,
      createdAt: "2026-04-17T14:30:00Z",
    },
    {
      id: 18,
      title: "Maintenance Notice",
      message: "SecureMail will undergo scheduled maintenance on May 5th, 02:00 UTC.",
      type: "warning",
      category: "system",
      isRead: true,
      createdAt: "2026-04-16T12:00:00Z",
    },
    {
      id: 19,
      title: "Malware Detected & Removed",
      message: "An attachment in a recent email was found to contain malware and was removed.",
      type: "error",
      category: "threats",
      isRead: false,
      createdAt: "2026-04-15T16:45:00Z",
    },
    {
      id: 20,
      title: "New Newsletter Out",
      message: "Check out our latest tips for staying safe online in this month's newsletter.",
      type: "info",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-14T09:00:00Z",
    },
    {
      id: 21,
      title: "Password Recovery Email Sent",
      message: "A password recovery email was sent per your request.",
      type: "info",
      category: "system",
      isRead: true,
      createdAt: "2026-04-13T11:20:00Z",
    },
    {
      id: 22,
      title: "Team Member Added",
      message: "John Doe has been added to your organization's team account.",
      type: "success",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-12T15:10:00Z",
    },
    {
      id: 23,
      title: "Unrecognized Extension Blocked",
      message: "A message containing an unrecognized file extension was blocked.",
      type: "error",
      category: "threats",
      isRead: false,
      createdAt: "2026-04-11T20:30:00Z",
    },
    {
      id: 24,
      title: "Discount Code Applied",
      message: "You've successfully applied a 20% discount to your next billing cycle.",
      type: "success",
      category: "system",
      isRead: true,
      createdAt: "2026-04-10T12:00:00Z",
    },
    {
      id: 25,
      title: "Weekly Summary: 0 Threats",
      message: "Great news! No threats were detected in your account this week.",
      type: "success",
      category: "threats",
      isRead: true,
      createdAt: "2026-04-09T08:00:00Z",
    },
    {
      id: 26,
      title: "New Feature: Email Scheduling",
      message: "You can now schedule your emails to be sent at a later time.",
      type: "info",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-08T14:45:00Z",
    },
    {
      id: 27,
      title: "Account Verified",
      message: "Your account identity has been successfully verified.",
      type: "success",
      category: "system",
      isRead: true,
      createdAt: "2026-04-07T10:15:00Z",
    },
    {
      id: 28,
      title: "Spam Filter Updated",
      message: "Our spam filter has been improved to catch even more junk mail.",
      type: "success",
      category: "updates",
      isRead: true,
      createdAt: "2026-04-06T19:20:00Z",
    },
    {
      id: 29,
      title: "Domain Verification Pending",
      message: "Please verify your domain ownership to continue using custom emails.",
      type: "warning",
      category: "system",
      isRead: false,
      createdAt: "2026-04-05T13:40:00Z",
    }
  ],
  total: 29,
  page: 1,
  totalPages: 2,
};
